import React, { useState } from 'react';
import { UploadCloud, FileType, CheckCircle, Download, BookOpen, Hexagon, Image as ImageIcon, Loader2 } from 'lucide-react';
import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import './App.css';

function App() {
  const [file, setFile] = useState(null);
  const [isDragging, setIsDragging] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  
  const [data, setData] = useState(null);
  const [activeTab, setActiveTab] = useState('chapters'); // 'chapters' or 'images'
  const [viewModes, setViewModes] = useState({}); // tracking hex/text mode per chapter index

  const handleDragOver = (e) => {
    e.preventDefault();
    setIsDragging(true);
  };

  const handleDragLeave = (e) => {
    e.preventDefault();
    setIsDragging(false);
  };

  const handleDrop = (e) => {
    e.preventDefault();
    setIsDragging(false);
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      handleFileChange(e.dataTransfer.files[0]);
    }
  };

  const handleFileChange = async (selectedFile) => {
    if (selectedFile?.type !== 'application/pdf') {
      setError('Please upload a valid PDF document.');
      return;
    }
    setError(null);
    setFile(selectedFile);
    await uploadContent(selectedFile);
  };

  const uploadContent = async (selectedFile) => {
    setLoading(true);
    setData(null);
    try {
      const formData = new FormData();
      formData.append('file', selectedFile);

      const response = await fetch('http://localhost:8000/upload/', {
        method: 'POST',
        body: formData,
      });

      if (!response.ok) {
        throw new Error('Server error while processing PDF');
      }

      const result = await response.json();
      setData(result);
      
      const initialModes = {};
      result.chapters.forEach((_, i) => initialModes[i] = 'text');
      setViewModes(initialModes);

    } catch (err) {
      setError(err.message || 'An error occurred during upload.');
    } finally {
      setLoading(false);
    }
  };

  const toggleMode = (idx, mode) => {
    setViewModes(prev => ({ ...prev, [idx]: mode }));
  };

  const generateXHTML = (title, content, isHex) => {
    const escapeHTML = (str) => {
      if (typeof str !== 'string') return str;
      return str
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#39;');
    };
    
    const safeTitle = escapeHTML(title);
    const safeContent = isHex ? content : content; // For text mode, content is valid HTML generated by backend

    // Generate valid EPUB 3 compliant XHTML
    return `<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html>
<html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" xmlns:svg="http://www.w3.org/2000/svg">
<head>
<title>${safeTitle}</title>
<link href="../styles/9780821379721.css" rel="stylesheet" type="text/css"/>
<link href="../styles/synth.css" rel="stylesheet" type="text/css"/>
<style type="text/css">
/* Layout overrides required for accurate PyMuPDF content mapping */
body { margin: 0; padding: 0; }
.hex-dump { font-family: monospace; word-break: break-all; color: #8b5cf6; }
div[id^="page"] {
    position: relative;
    background-color: white;
    margin: 0 auto 2rem auto;
    overflow: hidden;
}
div[id^="page"] p {
    position: absolute;
    margin: 0;
    white-space: pre;
}
</style>
</head>
<body epub:type="bodymatter" class="chapter-pg">
<section epub:type="chapter" id="chapter-content">
${isHex ? `<div class="hex-dump">\n${safeContent}\n</div>` : `<div>\n${safeContent}\n</div>`}
</section>
</body>
</html>`;
  };

  const handleExport = async () => {
    if (!data) return;
    
    const zip = new JSZip();
    
    // Create chapter items
    const chaptersFolder = zip.folder("chapters");
    data.chapters.forEach((ch, idx) => {
      // Determine what to save based on user's current view, or save both. We'll save the currently selected view
      const mode = viewModes[idx] || 'text';
      const content = mode === 'hex' ? ch.hex : ch.text;
      const xhtmlStr = generateXHTML(ch.title, content, mode === 'hex');
      
      const safeTitle = ch.title.replace(/[^a-z0-9]/gi, '_').toLowerCase();
      chaptersFolder.file(`chapter_${idx + 1}_${safeTitle || 'untitled'}.xhtml`, xhtmlStr);
    });

    // Create images folder
    if (data.images && data.images.length > 0) {
      const imagesFolder = zip.folder("images");
      data.images.forEach((img, idx) => {
        // Base64 to blob
        imagesFolder.file(`image_page${img.page}_${idx + 1}.${img.ext}`, img.data, { base64: true });
      });
    }

    const blob = await zip.generateAsync({ type: "blob" });
    saveAs(blob, `${data.filename.replace('.pdf', '')}_export.zip`);
  };

  return (
    <div className="app-container">
      <header className="header">
        <BookOpen className="header-icon" />
        <h1 className="title">Book Digitalizer</h1>
        <p className="subtitle">
          Transform your PDFs into structured, intelligent data. Extract chapters, translate text to Hexadecimal, and export as beautiful XHTML & media arrays.
        </p>
      </header>

      {!data && !loading && (
        <label 
          className={`upload-container ${isDragging ? 'dragging' : ''}`}
          onDragOver={handleDragOver}
          onDragLeave={handleDragLeave}
          onDrop={handleDrop}
        >
          <UploadCloud size={64} className="upload-icon" />
          <div className="upload-text">Click to upload or drag and drop</div>
          <div className="upload-subtext">Supports PDF format up to 50MB</div>
          <input type="file" accept="application/pdf" onChange={(e) => {
            if (e.target.files && e.target.files[0]) handleFileChange(e.target.files[0]);
          }} />
        </label>
      )}

      {error && <div style={{ color: '#ef4444', textAlign: 'center', marginTop: '1rem' }}>{error}</div>}

      {loading && (
        <div className="loading-container">
          <div className="spinner"></div>
          <div style={{ color: 'var(--accent-primary)', fontSize: '1.2rem', fontWeight: 500 }}>
            Analyzing deep document structure...
          </div>
        </div>
      )}

      {data && !loading && (
        <main className="dashboard">
          <div className="dashboard-header">
            <div className="dashboard-title">
              <CheckCircle color="#10b981" />
              <span>Processed {data.filename}</span>
            </div>
            <div className="dashboard-actions">
              <button className="btn" onClick={handleExport}>
                <Download size={18} /> Export as XHTML Archive
              </button>
            </div>
          </div>

          <div className="tabs">
            <button 
              className={`tab ${activeTab === 'chapters' ? 'active' : ''}`}
              onClick={() => setActiveTab('chapters')}
            >
              Extracted Content ({data.chapters.length})
            </button>
            <button 
              className={`tab ${activeTab === 'images' ? 'active' : ''}`}
              onClick={() => setActiveTab('images')}
            >
              Document Media ({data.images.length})
            </button>
          </div>

          {activeTab === 'chapters' && (
            <div className="chapter-list">
              {data.chapters.map((ch, idx) => (
                <div key={idx} className="chapter-card">
                  <div className="chapter-header">
                    <span className="chapter-title">{ch.title || `Section ${idx + 1}`}</span>
                    <div className="toggle-group">
                      <button 
                        className={`toggle-btn ${viewModes[idx] === 'text' ? 'active' : ''}`}
                        onClick={() => toggleMode(idx, 'text')}
                      >
                        Text View
                      </button>
                      <button 
                         className={`toggle-btn ${viewModes[idx] === 'hex' ? 'active' : ''}`}
                         onClick={() => toggleMode(idx, 'hex')}
                      >
                        <Hexagon size={14} style={{ display: 'inline', marginRight: '4px', verticalAlign: 'middle' }}/>
                        Hex View
                      </button>
                    </div>
                  </div>
                  <div className={`chapter-body ${viewModes[idx] === 'text' ? 'text-mode' : 'hex-mode'}`}>
                    {viewModes[idx] === 'text' ? <div dangerouslySetInnerHTML={{ __html: ch.text }} /> : ch.hex}
                  </div>
                </div>
              ))}
            </div>
          )}

          {activeTab === 'images' && (
            <div className="images-grid">
              {data.images.length === 0 ? (
                <div style={{color: 'var(--text-muted)'}}>No images detected in this document.</div>
              ) : (
                data.images.map((img, idx) => (
                  <div key={idx} className="image-card">
                     <img src={`data:image/${img.ext};base64,${img.data}`} alt={`Page ${img.page} media`} loading="lazy" />
                     <div className="image-overlay">
                       <span className="image-label">Page {img.page}</span>
                       <ImageIcon size={16} color="white" />
                     </div>
                  </div>
                ))
              )}
            </div>
          )}
        </main>
      )}
    </div>
  );
}

export default App;
